.Dd $Mdocdate$
.Dt neocd 1
.Os
.
.Sh NAME
.Nm neocd
.Nd simple wrapper
.
.Sh DESCRYPTION
The
.Nm 
is simple wrapper for custom cd states.
.
.Sh EXIT STATUS
.Ex -std
.
.Sh STANDARTS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification.
.
.Sh NOTES
For install the
.Nm
you need to add alias with "source neocd1"
for you custom cd.
.
.Sh AUTHORS
.An gimura Aq gimura0001@gmail.com
